# Buyer Segmentation and Investment Profiling for Real Estate Market Intelligence

## Data Understanding

This notebook performs the initial exploration of the buyer and property datasets.

Objectives:

- Load and inspect the datasets
- Understand dataset dimensions
- Examine data types
- Identify missing values
- Detect duplicate records
- Explore categorical and numerical variables
- Assess data quality before preprocessing
- Evaluate merge feasibility between client and property datasets

Author: Jeffrin Merino J

Project: Unified Mentor – Parcl Co. Limited

In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [2]:
clients = pd.read_csv("../data/raw/clients.csv")
properties = pd.read_csv("../data/raw/properties.csv")

print("Clients dataset loaded successfully.")
print("Properties dataset loaded successfully.")

Clients dataset loaded successfully.
Properties dataset loaded successfully.

In [3]:
print("Clients Shape:", clients.shape)
print("Properties Shape:", properties.shape)

Clients Shape: (2000, 12)
Properties Shape: (10000, 9)

In [5]:
clients.head()

,client_id,client_type,first_name,last_name,date_of_birth,gender,country,region,acquisition_purpose,satisfaction_score,loan_applied,referral_channel
0,C0001,Individual,Kareem,Liu,05-11-1968,F,USA,California,Home,4,Yes,Website
1,C0002,Individual,Trystan,Oconnor,11/26/1962,M,USA,California,Home,1,No,Website
2,C0003,Individual,Kale,Gay,04-07-1959,M,USA,California,Home,4,Yes,Agency
3,C0004,Individual,Russell,Gross,11/25/1959,M,USA,California,Home,5,No,Website
4,C0005,Company,Marleez,Co,2/28/1976,M,USA,California,Investment,5,No,Website

In [6]:
properties.head()

,listing_id,tower_number,transaction_date,unit_category,unit_number,floor_area_sqft,sale_price,listing_status,client_ref
0,1012,1,01-01-2024,Apartment,12,1160.36,"$300,385.62",Sold,C0027
1,1015,1,01-01-2024,Apartment,15,782.25,"$208,930.81",Sold,C0097
2,1021,1,01-01-2024,Apartment,21,756.21,"$218,585.92",Sold,C0113
3,1030,1,01-01-2024,Apartment,30,743.09,"$246,172.68",Sold,C0141
4,2016,2,01-01-2024,Apartment,16,701.66,"$212,265.67",Sold,C0146

In [7]:
clients.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   client_id            2000 non-null   str
 1   client_type          2000 non-null   str
 2   first_name           2000 non-null   str
 3   last_name            2000 non-null   str
 4   date_of_birth        2000 non-null   str
 5   gender               2000 non-null   str
 6   country              2000 non-null   str
 7   region               2000 non-null   str
 8   acquisition_purpose  2000 non-null   str
 9   satisfaction_score   2000 non-null   int64
 10  loan_applied         2000 non-null   str
 11  referral_channel     2000 non-null   str
dtypes: int64(1), str(11)
memory usage: 312.6 KB

In [8]:
properties.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   listing_id        10000 non-null  int64
 1   tower_number      10000 non-null  int64
 2   transaction_date  10000 non-null  str
 3   unit_category     10000 non-null  str
 4   unit_number       10000 non-null  int64
 5   floor_area_sqft   10000 non-null  float64
 6   sale_price        10000 non-null  str
 7   listing_status    10000 non-null  str
 8   client_ref        7305 non-null   str
dtypes: float64(1), int64(3), str(5)
memory usage: 1.1 MB

In [9]:
clients.dtypes

client_id                str
client_type              str
first_name               str
last_name                str
date_of_birth            str
gender                   str
country                  str
region                   str
acquisition_purpose      str
satisfaction_score     int64
loan_applied             str
referral_channel         str
dtype: object

In [10]:
properties.dtypes

listing_id            int64
tower_number          int64
transaction_date        str
unit_category           str
unit_number           int64
floor_area_sqft     float64
sale_price              str
listing_status          str
client_ref              str
dtype: object

In [11]:
missing_clients = clients.isnull().sum().to_frame(name="Missing Values")
missing_clients["Percentage"] = (missing_clients["Missing Values"] / len(clients)) * 100
missing_clients

                     Missing Values  Percentage
client_id                         0         0.0
client_type                       0         0.0
first_name                        0         0.0
last_name                         0         0.0
date_of_birth                     0         0.0
gender                            0         0.0
country                           0         0.0
region                            0         0.0
acquisition_purpose               0         0.0
satisfaction_score                0         0.0
loan_applied                      0         0.0
referral_channel                  0         0.0

In [12]:
missing_properties = properties.isnull().sum().to_frame(name="Missing Values")
missing_properties["Percentage"] = (missing_properties["Missing Values"] / len(properties)) * 100
missing_properties

                  Missing Values  Percentage
listing_id                     0        0.00
tower_number                   0        0.00
transaction_date               0        0.00
unit_category                  0        0.00
unit_number                    0        0.00
floor_area_sqft                0        0.00
sale_price                     0        0.00
listing_status                 0        0.00
client_ref                  2695       26.95

In [13]:
print("Client duplicates:", clients.duplicated().sum())
print("Property duplicates:", properties.duplicated().sum())

Client duplicates: 0
Property duplicates: 0

In [14]:
for col in clients.columns:
    print(f"\\n{col}")
    print(clients[col].nunique())

\nclient_id
2000
\nclient_type
2
\nfirst_name
337
\nlast_name
224
\ndate_of_birth
1889
\ngender
2
\ncountry
10
\nregion
57
\nacquisition_purpose
2
\nsatisfaction_score
5
\nloan_applied
2
\nreferral_channel
3

In [15]:
clients.describe(include=[np.number])

       satisfaction_score
count         2000.000000
mean             3.029000
std              1.413562
min              1.000000
25%              2.000000
50%              3.000000
75%              4.000000
max              5.000000

In [16]:
properties.describe(include=[np.number])

          listing_id  tower_number  unit_number  floor_area_sqft
count   10000.000000  10000.000000  10000.00000     10000.000000
mean   105898.277400     10.370100     28.99920      1139.941412
std     74414.566199      5.769025     16.88242       418.373967
min      1002.000000      1.000000      1.00000       410.710000
25%     50389.750000      5.000000     15.00000       782.200000
50%    100404.500000     10.000000     29.00000      1110.880000
75%    150411.250000     15.000000     43.00000      1499.000000
max    990026.000000     20.000000     70.00000      1957.160000

In [17]:
clients.describe(include=["object"])

C:\Users\jeffr\AppData\Local\Temp\ipykernel_18088\401943611.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  clients.describe(include=["object"])

,client_id,client_type,first_name,last_name,date_of_birth,gender,country,region,acquisition_purpose,loan_applied,referral_channel
count,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000
unique,2000,2,337,224,1889,2,10,57,2,2,3
top,C0001,Individual,Carl,Co,4/13/1967,M,USA,California,Home,No,Website
freq,1,1897,24,103,3,1012,1538,633,1385,1264,1103

In [18]:
print("Unique client IDs:", clients["client_id"].nunique())
print("Unique property client references:", properties["client_ref"].nunique())

matched = properties["client_ref"].isin(clients["client_id"]).sum()

print("Matching property records:", matched)
print("Matching percentage:", round(matched / len(properties) * 100, 2), "%")

Unique client IDs: 2000
Unique property client references: 2000
Matching property records: 7305
Matching percentage: 73.05 %

## Initial observations

- The client dataset contains demographic and financing attributes.
- The property dataset contains investment transaction information.
- The datasets can potentially be merged using `client_id` and `client_ref`.
- Missing values and duplicate records will be handled during preprocessing.
- Date of birth will be transformed into age.
- Categorical variables will require encoding for clustering.